function normalisePunctuation(value) {
  return value
    .normalize('NFKC')
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201c\u201d]/g, '"')
    .replace(/[\u2013\u2014]/g, '-')
    .replace(/\u2026/g, '...')
}

export function escapeLatex(value) {
  const replacements = {
    '\\': '\\textbackslash{}',
    '{': '\\{',
    '}': '\\}',
    '$': '\\$',
    '&': '\\&',
    '#': '\\#',
    '%': '\\%',
    '_': '\\_',
    '~': '\\textasciitilde{}',
    '^': '\\textasciicircum{}',
  }
  return normalisePunctuation(value).replace(/[\\{}$&#%_~^]/g, (character) => replacements[character])
}

function safeWebUrl(value) {
  if (!value) return ''
  try {
    const candidate = /^[a-z][a-z\d+.-]*:/i.test(value) ? value : `https://${value}`
    const url = new URL(candidate)
    if (!['http:', 'https:'].includes(url.protocol)) return ''
    return url.href
      .replace(/\\/g, '%5C')
      .replace(/([%&#_{}])/g, '\\$1')
  } catch {
    return ''
  }
}

function linkedContact(value) {
  const href = safeWebUrl(value)
  return href ? `\\href{${href}}{\\underline{${escapeLatex(value)}}}` : escapeLatex(value)
}

function contactLine(contact) {
  const items = []
  if (contact.phone) items.push(escapeLatex(contact.phone))
  if (contact.email) items.push(`\\href{mailto:${escapeLatex(contact.email)}}{\\underline{${escapeLatex(contact.email)}}}`)
  for (const value of [contact.linkedin, contact.github, contact.portfolio]) {
    if (value) items.push(linkedContact(value))
  }
  return items.join(' $|$ ')
}

function itemList(bullets) {
  if (!bullets.length) return ''
  return `
      \\resumeItemListStart
${bullets.map((bullet) => `        \\resumeItem{${escapeLatex(bullet)}}`).join('\n')}
      \\resumeItemListEnd`
}

function educationSection(entries) {
  if (!entries.length) return ''
  return `
\\section{Education}
  \\resumeSubHeadingListStart
${entries.map((entry) => `    \\resumeSubheading
      {${escapeLatex(entry.school)}}{${escapeLatex(entry.location)}}
      {${escapeLatex(entry.qualification)}}{${escapeLatex(entry.dates)}}`).join('\n')}
  \\resumeSubHeadingListEnd
`
}

function experienceSection(entries) {
  if (!entries.length) return ''
  return `
\\section{Experience}
  \\resumeSubHeadingListStart
${entries.map((entry) => `    \\resumeSubheading
      {${escapeLatex(entry.role)}}{${escapeLatex(entry.dates)}}
      {${escapeLatex(entry.organisation)}}{${escapeLatex(entry.location)}}${itemList(entry.bullets)}`).join('\n')}
  \\resumeSubHeadingListEnd
`
}

function projectSection(entries) {
  if (!entries.length) return ''
  return `
\\section{Projects}
  \\resumeSubHeadingListStart
${entries.map((entry) => `    \\resumeProjectHeading
      {\\textbf{${escapeLatex(entry.name)}}${entry.technologies ? ` $|$ \\emph{${escapeLatex(entry.technologies)}}` : ''}}{${escapeLatex(entry.dates)}}${itemList(entry.bullets)}`).join('\n')}
  \\resumeSubHeadingListEnd
`
}

function skillsSection(entries) {
  if (!entries.length) return ''
  return `
\\section{Technical Skills}
 \\begin{itemize}[leftmargin=0.15in, label={}]
    \\small{\\item{
${entries.map((entry) => `     \\textbf{${escapeLatex(entry.label)}}{: ${escapeLatex(entry.skills)}}`).join(' \\\\\n')}
    }}
 \\end{itemize}
`
}

function customSections(sections) {
  return sections.map((section) => `
\\section{${escapeLatex(section.title)}}
  \\resumeItemListStart
${section.bullets.map((bullet) => `    \\resumeItem{${escapeLatex(bullet)}}`).join('\n')}
  \\resumeItemListEnd
`).join('')
}

export function buildLatex(resume) {
  return `%-------------------------
% Resume in LaTeX
% Author: Jake Gutierrez
% Based off of: https://github.com/sb2nov/resume
% License: MIT
% Generated by CGC Resume Builder
%-------------------------

\\documentclass[letterpaper,11pt]{article}

\\usepackage{latexsym}
\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage{marvosym}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}
\\input{glyphtounicode}

\\pagestyle{fancy}
\\fancyhf{}
\\fancyfoot{}
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}

\\addtolength{\\oddsidemargin}{-0.5in}
\\addtolength{\\evensidemargin}{-0.5in}
\\addtolength{\\textwidth}{1in}
\\addtolength{\\topmargin}{-.5in}
\\addtolength{\\textheight}{1.0in}

\\urlstyle{same}
\\raggedbottom
\\raggedright
\\setlength{\\tabcolsep}{0in}

\\titleformat{\\section}{
  \\vspace{-4pt}\\scshape\\raggedright\\large
}{}{0em}{}[\\color{black}\\titlerule \\vspace{-5pt}]

\\pdfgentounicode=1

\\newcommand{\\resumeItem}[1]{
  \\item\\small{{#1 \\vspace{-2pt}}}
}

\\newcommand{\\resumeSubheading}[4]{
  \\vspace{-2pt}\\item
    \\begin{tabular*}{0.97\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}
      \\textbf{#1} & #2 \\\\
      \\textit{\\small#3} & \\textit{\\small #4} \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeProjectHeading}[2]{
  \\item
    \\begin{tabular*}{0.97\\textwidth}{l@{\\extracolsep{\\fill}}r}
      \\small#1 & #2 \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\renewcommand\\labelitemi{$\\vcenter{\\hbox{\\tiny$\\bullet$}}$}
\\renewcommand\\labelitemii{$\\vcenter{\\hbox{\\tiny$\\bullet$}}$}
\\newcommand{\\resumeSubHeadingListStart}{\\begin{itemize}[leftmargin=0.15in, label={}]}
\\newcommand{\\resumeSubHeadingListEnd}{\\end{itemize}}
\\newcommand{\\resumeItemListStart}{\\begin{itemize}}
\\newcommand{\\resumeItemListEnd}{\\end{itemize}\\vspace{-5pt}}

\\begin{document}

\\begin{center}
  \\textbf{\\Huge \\scshape ${escapeLatex(resume.contact.fullName)}} \\\\ \\vspace{1pt}
  \\small ${contactLine(resume.contact)}
\\end{center}
${educationSection(resume.education)}${experienceSection(resume.experience)}${projectSection(resume.projects)}${skillsSection(resume.skills)}${customSections(resume.customSections)}
\\end{document}
`
}
